<a href="https://colab.research.google.com/github/pin164/Automated-Expense-Categorization/blob/main/Random_forest_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
# STEP 1
# Import  dependencies
!pip install category_encoders
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from pathlib import Path
from sklearn import tree
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.callbacks import Callback
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn import preprocessing
import category_encoders as ce

from google.colab import drive
drive.mount('/content/drive')



   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.0/82.0 kB 2.3 MB/s eta 0:00:00
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## Preprocessing

In [10]:
# STEP 2
#  Import and read the Cleaned_Invoice_4.csv
#/content/drive/MyDrive/Project 4/Automated-Expense-Categorization/Cleaned_Invoice_4.csv
application_df = pd.read_csv("/content/drive/MyDrive/Project 4/Automated-Expense-Categorization/Cleaned_Invoice_4.csv",encoding='latin1').iloc[:,:14]
application_df.head()

Vendor Month  Year         PO# Invoice Date Invoice#  \
0  vendor 1039   Apr  2021  4501190248   2021-04-30        4   
1  vendor 1039   Apr  2021  4501190248   2021-04-30        4   
2  vendor 1039   Apr  2021  4501190248   2021-04-30        4   
3  vendor 1039   Apr  2021  4501190248   2021-04-30        4   
4  vendor 1039   Apr  2021  4501180577   2021-04-30        5   

   total Invoice Amt          TRS  \
0         $18,850.00   SDS7089109   
1         $18,850.00   SDS7090144   
2         $18,850.00   SDS7089063   
3         $18,850.00   SDS7090248   
4         $18,850.00   SDS7089423   

                                             Project      Amount   \
0                         WSH LINK Replacement - D&I     $455.00    
1                         AIMS Replacement (PDO-217)   $3,575.00    
2                                     Petrinex - D&I     $877.50    
3  M3P Vitality Upgrade - Implementation Phase - ...   $4,062.50    
4               Civil Legal Billing System - Scoping   $5,005.00    

   Cost Centre     Order# Dept  
0       165239  300007147  FIN  
1       171318  930089792  BTT  
2       190230  300007150  ARD  
3       195006  300007300  JUS  
4       171318  300007265  JUS

In [11]:
# STEP 3
# extract beneficial columns only
####X_df = application_df[['Column2','PO#','TRS','Order#','Column3']]
X_df = application_df[['PO#','TRS','Order#']]
Y_df = application_df['Cost Centre']



Cost Centre
171318    2225
171293     869
171225     546
171194     394
165155     195
          ... 
175259       5
171190       5
171197       4
195496       3
165212       2
Name: count, Length: 73, dtype: int64

PO#       object
TRS       object
Order#     int64
dtype: object

In [12]:
#Step 4
# amend the data type of order to be an object
X_df.loc[:, 'Order#'] = X_df['Order#'].astype('object')

X_df.dtypes

<ipython-input-12-78b2616e01c1>:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[300007147 930089792 300007150 ... 300007069 300007069 300007069]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  X_df.loc[:, 'Order#'] = X_df['Order#'].astype('object')


PO#       object
TRS       object
Order#    object
dtype: object

0    165239
1    171318
2    190230
3    195006
4    171318
Name: Cost Centre, dtype: int64

In [14]:
#Step 5
# Ordinal encoding transforms the column of class names into a column of class integers. Ordinal encoding scheme maps columns to integers randomly
#application_df_encoded = pd.get_dummies(X_df)
#application_df_encoded

encoder = ce.OrdinalEncoder()
encoder.fit_transform(X_df).head()

PO#  TRS  Order#
0    1    1       1
1    1    2       2
2    1    3       3
3    1    4       4
4    2    5       5

NameError: name 'X' is not defined

In [17]:
#Drop Rows with Missing Target Values:
#remove the rows from both the feature set X and the target set Y_df that contain missing target values.
# Combine X and y to drop rows with missing target values
combined_df = pd.concat([encoder, Y_df], axis=1)

# Drop rows where the target variable is missing
combined_df.dropna(subset=['Cost Centre'], inplace=True)

# Separate the features and target again after dropping missing values
X = combined_df.drop(columns=['Cost Centre']).values
y = combined_df['Cost Centre'].values


# Re-split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Display the shapes of the resulting datasets to verify the split
print("Training Features Shape:", X_train.shape)
print("Testing Features Shape:", X_test.shape)
print("Training Target Shape:", y_train.shape)
print("Testing Target Shape:", y_test.shape)



TypeError: cannot concatenate object of type '<class 'category_encoders.ordinal.OrdinalEncoder'>'; only Series and DataFrame objs are valid

In [ ]:
# Step 1: Import the DecisionTreeClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

# Step 2: Initialize the Decision Tree Model
dt_model = DecisionTreeClassifier(random_state=42)
# Increase the depth of the tree or minimum number of samples required to split
dt_model = DecisionTreeClassifier(random_state=42, max_depth=10, min_samples_split=5)

# Step 3: Train the Model on the Training Data
dt_model.fit(X_train, y_train)

# Step 4: Make Predictions on the Test Data
y_pred = dt_model.predict(X_test)





In [ ]:
# Check the distribution of target values
print(pd.Series(y_train).value_counts())


171318    1783
171293     695
171225     427
171194     315
165155     159
          ... 
175828       5
175259       5
171197       4
171190       3
195496       2
Name: count, Length: 72, dtype: int64


In [ ]:
# Step 5: Evaluate the Model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")

print("Classification Report:")
print(classification_report(y_test, y_pred, zero_division=1))

confusion = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion)


Accuracy: 0.4416
Classification Report:
              precision    recall  f1-score   support

      110508       1.00      0.00      0.00         8
      110889       1.00      0.00      0.00        13
      111173       1.00      0.00      0.00        15
      111508       1.00      0.00      0.00        21
      135072       1.00      0.00      0.00        12
      135139       1.00      0.00      0.00         5
      135150       1.00      0.00      0.00        13
      135367       1.00      0.00      0.00         7
      140010       1.00      1.00      1.00        15
      140548       1.00      0.00      0.00        19
      140642       1.00      0.00      0.00         4
      160207       1.00      0.00      0.00         2
      160781       1.00      0.00      0.00         3
      160996       1.00      0.00      0.00         4
      161017       1.00      0.00      0.00        10
      163124       1.00      0.00      0.00         5
      165031       1.00      0.00      0.

In [ ]:
from sklearn.ensemble import RandomForestClassifier

# Initialize the model
rf_model = RandomForestClassifier(random_state=42)

In [ ]:
#Some Cost Centres dominate the dataset,
# the model could struggle to predict minority payees.
# Use SMOTE or class weights.

# Using Class Weights:
rf_model = RandomForestClassifier(class_weight='balanced', random_state=42)
rf_model.fit(X_train, y_train)
y_pred = rf_model.predict(X_test)
print(classification_report(y_test, y_pred, zero_division=1))



              precision    recall  f1-score   support

      110508       1.00      1.00      1.00         8
      110889       1.00      1.00      1.00        13
      111173       1.00      1.00      1.00        15
      111508       1.00      1.00      1.00        21
      135072       1.00      1.00      1.00        12
      135139       1.00      1.00      1.00         5
      135150       1.00      1.00      1.00        13
      135367       1.00      1.00      1.00         7
      140010       1.00      1.00      1.00        15
      140548       1.00      1.00      1.00        19
      140642       1.00      1.00      1.00         4
      160207       1.00      1.00      1.00         2
      160781       1.00      1.00      1.00         3
      160996       1.00      1.00      1.00         4
      161017       1.00      1.00      1.00        10
      163124       1.00      1.00      1.00         5
      165031       1.00      1.00      1.00         9
      165039       1.00    

In [ ]:
#Using SMOTE to Balance Classes:
from imblearn.over_sampling import SMOTE

sm = SMOTE(random_state=42)
X_train_balanced, y_train_balanced = sm.fit_resample(X_train, y_train)


TypeError: numpy boolean subtract, the `-` operator, is not supported, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

In [ ]:


# Train the model
rf_model.fit(X_train, y_train)

# Make predictions and evaluate
y_pred = rf_model.predict(X_test)
print(classification_report(y_test, y_pred, zero_division=1))

              precision    recall  f1-score   support

      110508       1.00      1.00      1.00         8
      110889       1.00      1.00      1.00        13
      111173       1.00      1.00      1.00        15
      111508       1.00      1.00      1.00        21
      135072       1.00      1.00      1.00        12
      135139       1.00      1.00      1.00         5
      135150       1.00      1.00      1.00        13
      135367       1.00      1.00      1.00         7
      140010       1.00      1.00      1.00        15
      140548       1.00      1.00      1.00        19
      140642       1.00      1.00      1.00         4
      160207       1.00      1.00      1.00         2
      160781       1.00      1.00      1.00         3
      160996       1.00      1.00      1.00         4
      161017       1.00      1.00      1.00        10
      163124       1.00      1.00      1.00         5
      165031       1.00      1.00      1.00         9
      165039       1.00    

In [ ]:
rf_confusion = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(rf_confusion)

Confusion Matrix:
[[62  0  0 ...  0  0  0]
 [ 0 22  0 ...  0  0  0]
 [ 0  0 16 ...  0  0  0]
 ...
 [ 0  0  0 ... 10  0  0]
 [ 0  0  0 ...  0  8  0]
 [ 0  0  0 ...  0  0 17]]
